name: Build

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode-version: [11.5, 12.0, 12.3]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@1.0
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Bundler Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Pods Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cocoapods
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Xcake
      run: |
        bundle exec xcake make

    - name: Build
      run: |
        xcodebuild -workspace DemoXcoed.xcworkspace -scheme DemoXcoed -sdk iphonesimulator -arch x86_64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
